import React from 'react';

const ThirdPartyLicensesPage = ({ onNavigate, currentPage }) => {
  return (
    <main style={{ maxWidth: 1200, margin: '0 auto', padding: '40px 24px', lineHeight: 1.7, textAlign: 'left' }}>
      <div style={layoutStyle}>
        <Sidebar onNavigate={onNavigate} currentPage={currentPage} />

        <section style={contentStyle}>
          <div style={headerStickyStyle}>
            <h1 id="thirdparty" style={{ marginBottom: 8 }}>Third-Party Licenses & Attribution Policy</h1>
            <h2 style={{ marginTop: 0, fontSize: 18, fontWeight: 600 }}>Wild Mind AI by Wild Child Studios</h2>
            <p style={{ marginTop: 0 }}><strong>Effective Date:</strong> October 4, 2025</p>
          </div>

          <p>
            This policy details the licensing obligations related to third-party software, models, and assets used by Wild Mind AI by Wild Child Studios and outlines the attribution requirements that users must follow when utilizing the Service's Output Content.
          </p>

          <h3 style={{ marginTop: 28 }}>1. Open Source and Third-Party Component Disclosure</h3>
          <p>
            The Wild Mind AI Service incorporates various open-source software (OSS) libraries, datasets, and proprietary Application Programming Interfaces (APIs) under licenses such as MIT, Apache 2.0, and Creative Commons.
          </p>
          <p>
            A full list of all incorporated OSS components and their corresponding licenses is maintained in our [Licenses Archive Link Placeholder].
          </p>
          <p>
            <strong>User Compliance:</strong> You acknowledge that your use of the Service requires compliance with the terms of these third-party licenses, and you agree to adhere to all restrictions and requirements contained therein.
          </p>

          <h3 style={{ marginTop: 28 }}>2. Model and Output Attribution Requirements</h3>
          <p>
            When you publicly share, display, or distribute Output Content generated by the Service, you must comply with any attribution requirements mandated by the underlying generative models or datasets used:
          </p>
          <ul>
            <li>
              <strong>Creative Commons (CC BY) Requirement:</strong> If an underlying model or dataset requires "Attribution" (CC BY), you must provide a clear and conspicuous attribution to "Wild Mind AI by Wild Child Studios" and, where specified, a link to the source of the licensed material in the accompanying metadata or description of the Output Content.
            </li>
            <li>
              <strong>NonCommercial (NC) Restrictions:</strong> If the Output Content is generated using a model or component governed by a NonCommercial (NC) restriction, your use of that specific Output Content for commercial purposes is strictly prohibited unless you are subscribed to a specific Enterprise or Commercial tier that explicitly covers the necessary commercial licensing clearances.
            </li>
          </ul>

          <h3 style={{ marginTop: 28 }}>3. Commercial Use Indemnification</h3>
          <p>
            If you use Output Content commercially in violation of an underlying NonCommercial (NC) or ShareAlike (SA) license restriction, you agree that this constitutes a breach of the AUP and the TOS. Your indemnification obligation (Section 2.6 of the TOS) shall cover any resulting claims, lawsuits, or penalties brought against Wild Mind AI by Wild Child Studios by the original licensor.
          </p>

          <h3 style={{ marginTop: 28 }}>4. Asset Licensing</h3>
          <p>
            All proprietary fonts, interface assets, and iconography utilized in the Wild Mind AI interface are used under valid commercial or open-source licenses. You are not granted any license to extract or reuse these assets independently of the Service.
          </p>
        </section>
      </div>
    </main>
  );
};

// Layout styles (kept inline for simplicity and to avoid external CSS requirements)
const layoutStyle = {
  display: 'grid',
  gridTemplateColumns: '260px 1fr',
  gap: 24
};

const sidebarStyle = {
  position: 'sticky',
  top: 24,
  alignSelf: 'start',
  height: 'fit-content',
  padding: 16,
  border: '1px solid #e5e7eb',
  borderRadius: 8,
  background: '#fafafa'
};

const sidebarListStyle = {
  listStyle: 'none',
  margin: '12px 0 0 0',
  padding: 0,
  display: 'flex',
  flexDirection: 'column',
  gap: 8
};

const sidebarLinkStyle = {
  color: '#0f172a',
  textDecoration: 'none',
  cursor: 'default'
};

const contentStyle = {
  minWidth: 0
};

const headerStickyStyle = {
  position: 'sticky',
  top: 0,
  background: 'white',
  paddingTop: 8,
  paddingBottom: 8,
  zIndex: 5
};

// Sidebar component with navigation
const Sidebar = ({ onNavigate, currentPage }) => {
  const items = [
    { id: 'aup', label: 'Acceptable Use Policy (AUP)', page: 'aup' },
    { id: 'api-terms', label: 'API Terms of Use', page: 'api-terms' },
    { id: 'cookie', label: 'Cookie Policy', page: 'cookie' },
    { id: 'dmca', label: 'DMCA Policy', page: 'dmca' },
    { id: 'privacy', label: 'Privacy Policy', page: 'privacy' },
    { id: 'relationship', label: 'Service Relationship & Terms Hierarchy Document', page: 'relationship' },
    { id: 'tos', label: 'Terms of Service (TOS)', page: 'tos' },
    { id: 'thirdparty', label: 'Third-Party Licenses & Attribution Policy', page: 'thirdparty' }
  ];

  const handleClick = (e, page) => {
    e.preventDefault();
    if (onNavigate) {
      onNavigate(page);
    }
  };

  return (
    <aside style={sidebarStyle}>
      <h3 style={{ margin: 0, fontSize: 16, fontWeight: 700 }}>Documentation</h3>
      <ul style={sidebarListStyle}>
        {items.map((item) => (
          <li key={item.id}>
            <a
              href="#"
              onClick={(e) => handleClick(e, item.page)}
              style={{
                ...sidebarLinkStyle,
                fontWeight: 500,
                backgroundColor: currentPage === item.page ? 'rgba(0,0,0,0.05)' : 'transparent',
                borderRadius: 6,
                padding: '8px 10px',
                display: 'block',
                cursor: 'pointer'
              }}
            >
              {item.label}
            </a>
          </li>
        ))}
      </ul>
    </aside>
  );
};

export default ThirdPartyLicensesPage;


